use super::*;


const EXAMPLE_INPUT_1 :&str = "\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
";

#[test]
fn test_1() {
	let eqs = parse(EXAMPLE_INPUT_1);
	assert_eq!(14, unique_with_antinode(&eqs));
	assert_eq!(34, unique_with_antinode_unlimited(&eqs));
}
